//! This library provides structures and enums for describing
//! AArch64 (ARMv8) instructions.

/////////////////////////
//~ yuraiz: Custom integers
typedef unsigned long long da64_u64;
typedef unsigned int da64_u32;

//~ yuraiz: Custom counted string
typedef struct da64_str8 da64_str8;
struct da64_str8 {
    const char* data;
    da64_u64 size;
};

#define da64_str8_lit(lit) \
    (da64_str8) { .data = lit, .size = sizeof(lit) - 1 }

/////////////////////////
//~ yuraiz: Main definitions

// The AArch64 instruction classes.
typedef enum DA64_InsnClass DA64_InsnClass;
enum DA64_InsnClass {
    DA64_InsnClass_AARCH64_MISC,
    DA64_InsnClass_ADDSUB_CARRY,
    DA64_InsnClass_ADDSUB_EXT,
    DA64_InsnClass_ADDSUB_IMM,
    DA64_InsnClass_ADDSUB_SHIFT,
    DA64_InsnClass_ASIMDALL,
    DA64_InsnClass_ASIMDDIFF,
    DA64_InsnClass_ASIMDELEM,
    DA64_InsnClass_ASIMDEXT,
    DA64_InsnClass_ASIMDIMM,
    DA64_InsnClass_ASIMDINS,
    DA64_InsnClass_ASIMDMISC,
    DA64_InsnClass_ASIMDPERM,
    DA64_InsnClass_ASIMDSAME,
    DA64_InsnClass_ASIMDSHF,
    DA64_InsnClass_ASIMDTBL,
    DA64_InsnClass_ASISDDIFF,
    DA64_InsnClass_ASISDELEM,
    DA64_InsnClass_ASISDLSE,
    DA64_InsnClass_ASISDLSEP,
    DA64_InsnClass_ASISDLSO,
    DA64_InsnClass_ASISDLSOP,
    DA64_InsnClass_ASISDMISC,
    DA64_InsnClass_ASISDONE,
    DA64_InsnClass_ASISDPAIR,
    DA64_InsnClass_ASISDSAME,
    DA64_InsnClass_ASISDSHF,
    DA64_InsnClass_BFLOAT16,
    DA64_InsnClass_BITFIELD,
    DA64_InsnClass_BRANCH_IMM,
    DA64_InsnClass_BRANCH_REG,
    DA64_InsnClass_COMPBRANCH,
    DA64_InsnClass_CONDBRANCH,
    DA64_InsnClass_CONDCMP_IMM,
    DA64_InsnClass_CONDCMP_REG,
    DA64_InsnClass_CONDSEL,
    DA64_InsnClass_CRYPTOAES,
    DA64_InsnClass_CRYPTOSHA2,
    DA64_InsnClass_CRYPTOSHA3,
    DA64_InsnClass_CRYPTOSM3,
    DA64_InsnClass_CRYPTOSM4,
    DA64_InsnClass_CSSC,
    DA64_InsnClass_DOTPRODUCT,
    DA64_InsnClass_DP_1SRC,
    DA64_InsnClass_DP_2SRC,
    DA64_InsnClass_DP_3SRC,
    DA64_InsnClass_EXCEPTION,
    DA64_InsnClass_EXTRACT,
    DA64_InsnClass_FLOAT2FIX,
    DA64_InsnClass_FLOAT2INT,
    DA64_InsnClass_FLOATCCMP,
    DA64_InsnClass_FLOATCMP,
    DA64_InsnClass_FLOATDP1,
    DA64_InsnClass_FLOATDP2,
    DA64_InsnClass_FLOATDP3,
    DA64_InsnClass_FLOATIMM,
    DA64_InsnClass_FLOATSEL,
    DA64_InsnClass_GCS,
    DA64_InsnClass_IC_SYSTEM,
    DA64_InsnClass_LDST_IMM10,
    DA64_InsnClass_LDST_IMM9,
    DA64_InsnClass_LDST_POS,
    DA64_InsnClass_LDST_REGOFF,
    DA64_InsnClass_LDST_UNPRIV,
    DA64_InsnClass_LDST_UNSCALED,
    DA64_InsnClass_LDSTEXCL,
    DA64_InsnClass_LDSTNAPAIR_OFFS,
    DA64_InsnClass_LDSTPAIR_INDEXED,
    DA64_InsnClass_LDSTPAIR_OFF,
    DA64_InsnClass_LOADLIT,
    DA64_InsnClass_LOG_IMM,
    DA64_InsnClass_LOG_SHIFT,
    DA64_InsnClass_LSE_ATOMIC,
    DA64_InsnClass_LSE128_ATOMIC,
    DA64_InsnClass_MOVEWIDE,
    DA64_InsnClass_PCRELADDR,
    DA64_InsnClass_RCPC3,
    DA64_InsnClass_SME_FP_SD,
    DA64_InsnClass_SME_INT_SD,
    DA64_InsnClass_SME_LDR,
    DA64_InsnClass_SME_MISC,
    DA64_InsnClass_SME_MOV,
    DA64_InsnClass_SME_PSEL,
    DA64_InsnClass_SME_SHIFT,
    DA64_InsnClass_SME_SIZE_12_BHS,
    DA64_InsnClass_SME_SIZE_12_HS,
    DA64_InsnClass_SME_SIZE_22_HSD,
    DA64_InsnClass_SME_SIZE_22,
    DA64_InsnClass_SME_START,
    DA64_InsnClass_SME_STOP,
    DA64_InsnClass_SME_STR,
    DA64_InsnClass_SME_SZ_23,
    DA64_InsnClass_SME2_MOV,
    DA64_InsnClass_SME2_MOVAZ,
    DA64_InsnClass_SVE_CPY,
    DA64_InsnClass_SVE_INDEX,
    DA64_InsnClass_SVE_INDEX1,
    DA64_InsnClass_SVE_LIMM,
    DA64_InsnClass_SVE_MISC,
    DA64_InsnClass_SVE_MOVPRFX,
    DA64_InsnClass_SVE_PRED_ZM,
    DA64_InsnClass_SVE_SHIFT_PRED,
    DA64_InsnClass_SVE_SHIFT_TSZ_BHSD,
    DA64_InsnClass_SVE_SHIFT_TSZ_HSD,
    DA64_InsnClass_SVE_SHIFT_UNPRED,
    DA64_InsnClass_SVE_SIZE_13,
    DA64_InsnClass_SVE_SIZE_BH,
    DA64_InsnClass_SVE_SIZE_BHS,
    DA64_InsnClass_SVE_SIZE_BHSD,
    DA64_InsnClass_SVE_SIZE_HSD,
    DA64_InsnClass_SVE_SIZE_HSD2,
    DA64_InsnClass_SVE_SIZE_SD,
    DA64_InsnClass_SVE_SIZE_SD2,
    DA64_InsnClass_SVE_SIZE_TSZ_BHS,
    DA64_InsnClass_SVE2_URQVS,
    DA64_InsnClass_TESTBRANCH,
    DA64_InsnClass_THE,
};

typedef enum DA64_InsnFeatureSet DA64_InsnFeatureSet;
enum DA64_InsnFeatureSet {
    DA64_InsnFeatureSet_AES,
    DA64_InsnFeatureSet_B16B16,
    DA64_InsnFeatureSet_BFLOAT16,
    DA64_InsnFeatureSet_BFLOAT16_SVE,
    DA64_InsnFeatureSet_CHK,
    DA64_InsnFeatureSet_COMPNUM,
    DA64_InsnFeatureSet_CRC,
    DA64_InsnFeatureSet_CSSC,
    DA64_InsnFeatureSet_D128,
    DA64_InsnFeatureSet_D128_THE,
    DA64_InsnFeatureSet_DOTPROD,
    DA64_InsnFeatureSet_F32MM_SVE,
    DA64_InsnFeatureSet_F64MM_SVE,
    DA64_InsnFeatureSet_FLAGM,
    DA64_InsnFeatureSet_FLAGMANIP,
    DA64_InsnFeatureSet_FP,
    DA64_InsnFeatureSet_FP_16_V8_2A,
    DA64_InsnFeatureSet_FP_F16,
    DA64_InsnFeatureSet_FRINTTS,
    DA64_InsnFeatureSet_GCS,
    DA64_InsnFeatureSet_HBC,
    DA64_InsnFeatureSet_I8MM,
    DA64_InsnFeatureSet_I8MM_SVE,
    DA64_InsnFeatureSet_ITE,
    DA64_InsnFeatureSet_JSCVT,
    DA64_InsnFeatureSet_LOR,
    DA64_InsnFeatureSet_LS64,
    DA64_InsnFeatureSet_LSE,
    DA64_InsnFeatureSet_LSE128,
    DA64_InsnFeatureSet_MEMTAG,
    DA64_InsnFeatureSet_MOPS,
    DA64_InsnFeatureSet_MOPS_MEMTAG,
    DA64_InsnFeatureSet_PAC,
    DA64_InsnFeatureSet_PREDRES,
    DA64_InsnFeatureSet_PREDRES2,
    DA64_InsnFeatureSet_RCPC,
    DA64_InsnFeatureSet_RCPC2,
    DA64_InsnFeatureSet_RCPC3,
    DA64_InsnFeatureSet_RDMA,
    DA64_InsnFeatureSet_SB,
    DA64_InsnFeatureSet_SHA2,
    DA64_InsnFeatureSet_SHA3,
    DA64_InsnFeatureSet_SIMD,
    DA64_InsnFeatureSet_SIMD_F16,
    DA64_InsnFeatureSet_SM4,
    DA64_InsnFeatureSet_SME,
    DA64_InsnFeatureSet_SME2,
    DA64_InsnFeatureSet_SME2P1,
    DA64_InsnFeatureSet_SME2_F64F64,
    DA64_InsnFeatureSet_SME2_I16I64,
    DA64_InsnFeatureSet_SME_F64F64,
    DA64_InsnFeatureSet_SME_I16I64,
    DA64_InsnFeatureSet_SVE,
    DA64_InsnFeatureSet_SVE2,
    DA64_InsnFeatureSet_SVE2AES,
    DA64_InsnFeatureSet_SVE2BITPERM,
    DA64_InsnFeatureSet_SVE2P1,
    DA64_InsnFeatureSet_SVE2SHA3,
    DA64_InsnFeatureSet_SVE2SM4,
    DA64_InsnFeatureSet_THE,
    DA64_InsnFeatureSet_TME,
    DA64_InsnFeatureSet_V8,
    DA64_InsnFeatureSet_V8R,
    DA64_InsnFeatureSet_WFXT,
    DA64_InsnFeatureSet_XS,
};

// The AArch64 instruction flags.
typedef da64_u64 DA64_InsnFlags;
static const DA64_InsnFlags DA64_InsnFlag_EMPTY = 0;
static const DA64_InsnFlags DA64_InsnFlag_HAS_ADVSIMD_SCALAR_SIZE = 1 << 0;
static const DA64_InsnFlags DA64_InsnFlag_HAS_ADVSIMV_GPRSIZE_IN_Q = 1 << 1;
static const DA64_InsnFlags DA64_InsnFlag_HAS_ADVSIMV_VEC_IN_Q = 1 << 2;
static const DA64_InsnFlags DA64_InsnFlag_HAS_ALIAS = 1 << 3;
static const DA64_InsnFlags DA64_InsnFlag_HAS_FPTYPE_FIELD = 1 << 4;
static const DA64_InsnFlags DA64_InsnFlag_HAS_LDS_SIZE_IN_BIT_22 = 1 << 5;
static const DA64_InsnFlags DA64_InsnFlag_HAS_LSE_SZ_FIELD = 1 << 6;
static const DA64_InsnFlags DA64_InsnFlag_HAS_NARROW = 1 << 7;
static const DA64_InsnFlags DA64_InsnFlag_HAS_N_FIELD = 1 << 8;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_1 = 1 << 9;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_2 = 1 << 10;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_3 = 1 << 11;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_4 = 1 << 12;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_5 = 1 << 13;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_6 = 1 << 14;
static const DA64_InsnFlags DA64_InsnFlag_HAS_OPCODE_DEPENDENT_FIELD_7 = 1 << 15;
static const DA64_InsnFlags DA64_InsnFlag_HAS_RCPC3_SIZE = 1 << 16;
static const DA64_InsnFlags DA64_InsnFlag_HAS_SF_FIELD = 1 << 17;
static const DA64_InsnFlags DA64_InsnFlag_HAS_SIZE = 1 << 18;
static const DA64_InsnFlags DA64_InsnFlag_HAS_SIZEQ_FIELD = 1 << 19;
static const DA64_InsnFlags DA64_InsnFlag_HAS_SPEC_DECODE_RULES = 1 << 20;
static const DA64_InsnFlags DA64_InsnFlag_IS_ALIAS = 1 << 21;
static const DA64_InsnFlags DA64_InsnFlag_IS_COND = 1 << 22;
static const DA64_InsnFlags DA64_InsnFlag_IS_SYS_READ = 1 << 23;
static const DA64_InsnFlags DA64_InsnFlag_IS_SYS_WRITE = 1 << 24;
static const DA64_InsnFlags DA64_InsnFlag_RESTRICTED_NEXT_INSN_SET = 1 << 25;

// The AArch64 instruction operand kinds.
typedef enum DA64_InsnOperandKind DA64_InsnOperandKind;
enum DA64_InsnOperandKind {
    DA64_InsnOperandKind_ADDR_ADRP,
    DA64_InsnOperandKind_ADDR_OFFSET,
    DA64_InsnOperandKind_ADDR_PCREL14,
    DA64_InsnOperandKind_ADDR_PCREL19,
    DA64_InsnOperandKind_ADDR_PCREL21,
    DA64_InsnOperandKind_ADDR_PCREL26,
    DA64_InsnOperandKind_ADDR_REGOFF,
    DA64_InsnOperandKind_ADDR_SIMM10,
    DA64_InsnOperandKind_ADDR_SIMM11,
    DA64_InsnOperandKind_ADDR_SIMM13,
    DA64_InsnOperandKind_ADDR_SIMM7,
    DA64_InsnOperandKind_ADDR_SIMM9,
    DA64_InsnOperandKind_ADDR_SIMPLE,
    DA64_InsnOperandKind_ADDR_UIMM12,
    DA64_InsnOperandKind_AIMM,
    DA64_InsnOperandKind_BARRIER_DSB_NXS,
    DA64_InsnOperandKind_BARRIER_GCSB,
    DA64_InsnOperandKind_BARRIER_ISB,
    DA64_InsnOperandKind_BARRIER_PSB,
    DA64_InsnOperandKind_BARRIER,
    DA64_InsnOperandKind_BIT_NUM,
    DA64_InsnOperandKind_BTI_TARGET,
    DA64_InsnOperandKind_CCMP_IMM,
    DA64_InsnOperandKind_COND,
    DA64_InsnOperandKind_COND1,
    DA64_InsnOperandKind_CRm,
    DA64_InsnOperandKind_CRn,
    DA64_InsnOperandKind_CSSC_SIMM8,
    DA64_InsnOperandKind_CSSC_UIMM8,
    DA64_InsnOperandKind_Ed,
    DA64_InsnOperandKind_Em,
    DA64_InsnOperandKind_Em16,
    DA64_InsnOperandKind_En,
    DA64_InsnOperandKind_EXCEPTION,
    DA64_InsnOperandKind_Fa,
    DA64_InsnOperandKind_FBITS,
    DA64_InsnOperandKind_Fd,
    DA64_InsnOperandKind_Fm,
    DA64_InsnOperandKind_Fn,
    DA64_InsnOperandKind_FPIMM,
    DA64_InsnOperandKind_FPIMM0,
    DA64_InsnOperandKind_Ft,
    DA64_InsnOperandKind_Ft2,
    DA64_InsnOperandKind_HALF,
    DA64_InsnOperandKind_IDX,
    DA64_InsnOperandKind_IMM_2,
    DA64_InsnOperandKind_IMM_MOV,
    DA64_InsnOperandKind_IMM_ROT1,
    DA64_InsnOperandKind_IMM_ROT2,
    DA64_InsnOperandKind_IMM_ROT3,
    DA64_InsnOperandKind_IMM_VLSL,
    DA64_InsnOperandKind_IMM_VLSR,
    DA64_InsnOperandKind_IMM,
    DA64_InsnOperandKind_IMM0,
    DA64_InsnOperandKind_IMMR,
    DA64_InsnOperandKind_IMMS,
    DA64_InsnOperandKind_LEt,
    DA64_InsnOperandKind_LIMM,
    DA64_InsnOperandKind_LSE128_Rt,
    DA64_InsnOperandKind_LSE128_Rt2,
    DA64_InsnOperandKind_LVn,
    DA64_InsnOperandKind_LVt_AL,
    DA64_InsnOperandKind_LVt,
    DA64_InsnOperandKind_MASK,
    DA64_InsnOperandKind_MOPS_ADDR_Rd,
    DA64_InsnOperandKind_MOPS_ADDR_Rs,
    DA64_InsnOperandKind_MOPS_WB_Rn,
    DA64_InsnOperandKind_NZCV,
    DA64_InsnOperandKind_PAIRREG_OR_XZR,
    DA64_InsnOperandKind_PAIRREG,
    DA64_InsnOperandKind_PRFOP,
    DA64_InsnOperandKind_PSTATEFIELD,
    DA64_InsnOperandKind_Ra,
    DA64_InsnOperandKind_RCPC3_ADDR_OFFSET,
    DA64_InsnOperandKind_RCPC3_ADDR_OPT_POSTIND,
    DA64_InsnOperandKind_RCPC3_ADDR_OPT_PREIND_WB,
    DA64_InsnOperandKind_RCPC3_ADDR_POSTIND,
    DA64_InsnOperandKind_RCPC3_ADDR_PREIND_WB,
    DA64_InsnOperandKind_Rd_SP,
    DA64_InsnOperandKind_Rd,
    DA64_InsnOperandKind_Rm_EXT,
    DA64_InsnOperandKind_Rm_SFT,
    DA64_InsnOperandKind_Rm_SP,
    DA64_InsnOperandKind_Rm,
    DA64_InsnOperandKind_Rn_SP,
    DA64_InsnOperandKind_Rn,
    DA64_InsnOperandKind_RPRFMOP,
    DA64_InsnOperandKind_Rs,
    DA64_InsnOperandKind_Rt_LS64,
    DA64_InsnOperandKind_Rt_SP,
    DA64_InsnOperandKind_Rt_SYS,
    DA64_InsnOperandKind_Rt,
    DA64_InsnOperandKind_Rt2,
    DA64_InsnOperandKind_Sd,
    DA64_InsnOperandKind_SHLL_IMM,
    DA64_InsnOperandKind_SIMD_ADDR_POST,
    DA64_InsnOperandKind_SIMD_ADDR_SIMPLE,
    DA64_InsnOperandKind_SIMD_FPIMM,
    DA64_InsnOperandKind_SIMD_IMM_SFT,
    DA64_InsnOperandKind_SIMD_IMM,
    DA64_InsnOperandKind_SIMM5,
    DA64_InsnOperandKind_Sm,
    DA64_InsnOperandKind_SME_ADDR_RI_U4xVL,
    DA64_InsnOperandKind_SME_list_of_64bit_tiles,
    DA64_InsnOperandKind_SME_Pdx2,
    DA64_InsnOperandKind_SME_PdxN,
    DA64_InsnOperandKind_SME_Pm,
    DA64_InsnOperandKind_SME_PNd3,
    DA64_InsnOperandKind_SME_PNg3,
    DA64_InsnOperandKind_SME_PNn,
    DA64_InsnOperandKind_SME_PNn3_INDEX1,
    DA64_InsnOperandKind_SME_PNn3_INDEX2,
    DA64_InsnOperandKind_SME_PnT_Wm_imm,
    DA64_InsnOperandKind_SME_SHRIMM4,
    DA64_InsnOperandKind_SME_SHRIMM5,
    DA64_InsnOperandKind_SME_SM_ZA,
    DA64_InsnOperandKind_SME_VLxN_10,
    DA64_InsnOperandKind_SME_VLxN_13,
    DA64_InsnOperandKind_SME_ZA_array_off1x4,
    DA64_InsnOperandKind_SME_ZA_array_off2x2,
    DA64_InsnOperandKind_SME_ZA_array_off2x4,
    DA64_InsnOperandKind_SME_ZA_array_off3_0,
    DA64_InsnOperandKind_SME_ZA_array_off3_5,
    DA64_InsnOperandKind_SME_ZA_array_off3x2,
    DA64_InsnOperandKind_SME_ZA_array_off4,
    DA64_InsnOperandKind_SME_ZA_array_vrsb_1,
    DA64_InsnOperandKind_SME_ZA_array_vrsb_2,
    DA64_InsnOperandKind_SME_ZA_array_vrsd_1,
    DA64_InsnOperandKind_SME_ZA_array_vrsd_2,
    DA64_InsnOperandKind_SME_ZA_array_vrsh_1,
    DA64_InsnOperandKind_SME_ZA_array_vrsh_2,
    DA64_InsnOperandKind_SME_ZA_array_vrss_1,
    DA64_InsnOperandKind_SME_ZA_array_vrss_2,
    DA64_InsnOperandKind_SME_ZA_HV_idx_dest,
    DA64_InsnOperandKind_SME_ZA_HV_idx_destxN,
    DA64_InsnOperandKind_SME_ZA_HV_idx_ldstr,
    DA64_InsnOperandKind_SME_ZA_HV_idx_src,
    DA64_InsnOperandKind_SME_ZA_HV_idx_srcxN,
    DA64_InsnOperandKind_SME_ZAda_2b,
    DA64_InsnOperandKind_SME_ZAda_3b,
    DA64_InsnOperandKind_SME_Zdnx2,
    DA64_InsnOperandKind_SME_Zdnx4,
    DA64_InsnOperandKind_SME_Zm_INDEX1,
    DA64_InsnOperandKind_SME_Zm_INDEX2,
    DA64_InsnOperandKind_SME_Zm_INDEX3_1,
    DA64_InsnOperandKind_SME_Zm_INDEX3_10,
    DA64_InsnOperandKind_SME_Zm_INDEX3_2,
    DA64_InsnOperandKind_SME_Zm_INDEX4_1,
    DA64_InsnOperandKind_SME_Zm_INDEX4_10,
    DA64_InsnOperandKind_SME_Zm,
    DA64_InsnOperandKind_SME_Zmx2,
    DA64_InsnOperandKind_SME_Zmx4,
    DA64_InsnOperandKind_SME_Zn_INDEX1_16,
    DA64_InsnOperandKind_SME_Zn_INDEX2_15,
    DA64_InsnOperandKind_SME_Zn_INDEX2_16,
    DA64_InsnOperandKind_SME_Zn_INDEX3_14,
    DA64_InsnOperandKind_SME_Zn_INDEX3_15,
    DA64_InsnOperandKind_SME_Zn_INDEX4_14,
    DA64_InsnOperandKind_SME_Znx2,
    DA64_InsnOperandKind_SME_Znx4,
    DA64_InsnOperandKind_SME_ZT0_INDEX,
    DA64_InsnOperandKind_SME_ZT0_LIST,
    DA64_InsnOperandKind_SME_ZT0,
    DA64_InsnOperandKind_SME_Zt2,
    DA64_InsnOperandKind_SME_Zt3,
    DA64_InsnOperandKind_SME_Zt4,
    DA64_InsnOperandKind_SME_Ztx2_STRIDED,
    DA64_InsnOperandKind_SME_Ztx4_STRIDED,
    DA64_InsnOperandKind_Sn,
    DA64_InsnOperandKind_SVE_ADDR_R,
    DA64_InsnOperandKind_SVE_ADDR_RI_S4x16,
    DA64_InsnOperandKind_SVE_ADDR_RI_S4x2xVL,
    DA64_InsnOperandKind_SVE_ADDR_RI_S4x32,
    DA64_InsnOperandKind_SVE_ADDR_RI_S4x3xVL,
    DA64_InsnOperandKind_SVE_ADDR_RI_S4x4xVL,
    DA64_InsnOperandKind_SVE_ADDR_RI_S4xVL,
    DA64_InsnOperandKind_SVE_ADDR_RI_S6xVL,
    DA64_InsnOperandKind_SVE_ADDR_RI_S9xVL,
    DA64_InsnOperandKind_SVE_ADDR_RI_U6,
    DA64_InsnOperandKind_SVE_ADDR_RI_U6x2,
    DA64_InsnOperandKind_SVE_ADDR_RI_U6x4,
    DA64_InsnOperandKind_SVE_ADDR_RI_U6x8,
    DA64_InsnOperandKind_SVE_ADDR_RR_LSL1,
    DA64_InsnOperandKind_SVE_ADDR_RR_LSL2,
    DA64_InsnOperandKind_SVE_ADDR_RR_LSL3,
    DA64_InsnOperandKind_SVE_ADDR_RR_LSL4,
    DA64_InsnOperandKind_SVE_ADDR_RR,
    DA64_InsnOperandKind_SVE_ADDR_RX_LSL1,
    DA64_InsnOperandKind_SVE_ADDR_RX_LSL2,
    DA64_InsnOperandKind_SVE_ADDR_RX_LSL3,
    DA64_InsnOperandKind_SVE_ADDR_RX,
    DA64_InsnOperandKind_SVE_ADDR_RZ_LSL1,
    DA64_InsnOperandKind_SVE_ADDR_RZ_LSL2,
    DA64_InsnOperandKind_SVE_ADDR_RZ_LSL3,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW_14,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW_22,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW1_14,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW1_22,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW2_14,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW2_22,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW3_14,
    DA64_InsnOperandKind_SVE_ADDR_RZ_XTW3_22,
    DA64_InsnOperandKind_SVE_ADDR_RZ,
    DA64_InsnOperandKind_SVE_ADDR_ZI_U5,
    DA64_InsnOperandKind_SVE_ADDR_ZI_U5x2,
    DA64_InsnOperandKind_SVE_ADDR_ZI_U5x4,
    DA64_InsnOperandKind_SVE_ADDR_ZI_U5x8,
    DA64_InsnOperandKind_SVE_ADDR_ZX,
    DA64_InsnOperandKind_SVE_ADDR_ZZ_LSL,
    DA64_InsnOperandKind_SVE_ADDR_ZZ_SXTW,
    DA64_InsnOperandKind_SVE_ADDR_ZZ_UXTW,
    DA64_InsnOperandKind_SVE_AIMM,
    DA64_InsnOperandKind_SVE_ASIMM,
    DA64_InsnOperandKind_SVE_FPIMM8,
    DA64_InsnOperandKind_SVE_I1_HALF_ONE,
    DA64_InsnOperandKind_SVE_I1_HALF_TWO,
    DA64_InsnOperandKind_SVE_I1_ZERO_ONE,
    DA64_InsnOperandKind_SVE_IMM_ROT1,
    DA64_InsnOperandKind_SVE_IMM_ROT2,
    DA64_InsnOperandKind_SVE_IMM_ROT3,
    DA64_InsnOperandKind_SVE_INV_LIMM,
    DA64_InsnOperandKind_SVE_LIMM_MOV,
    DA64_InsnOperandKind_SVE_LIMM,
    DA64_InsnOperandKind_SVE_PATTERN_SCALED,
    DA64_InsnOperandKind_SVE_PATTERN,
    DA64_InsnOperandKind_SVE_Pd,
    DA64_InsnOperandKind_SVE_Pg3,
    DA64_InsnOperandKind_SVE_Pg4_10,
    DA64_InsnOperandKind_SVE_Pg4_16,
    DA64_InsnOperandKind_SVE_Pg4_5,
    DA64_InsnOperandKind_SVE_Pm,
    DA64_InsnOperandKind_SVE_Pn,
    DA64_InsnOperandKind_SVE_PNd,
    DA64_InsnOperandKind_SVE_PNg4_10,
    DA64_InsnOperandKind_SVE_PNn,
    DA64_InsnOperandKind_SVE_PNt,
    DA64_InsnOperandKind_SVE_PRFOP,
    DA64_InsnOperandKind_SVE_Pt,
    DA64_InsnOperandKind_SVE_Rm,
    DA64_InsnOperandKind_SVE_Rn_SP,
    DA64_InsnOperandKind_SVE_SHLIMM_PRED,
    DA64_InsnOperandKind_SVE_SHLIMM_UNPRED_22,
    DA64_InsnOperandKind_SVE_SHLIMM_UNPRED,
    DA64_InsnOperandKind_SVE_SHRIMM_PRED,
    DA64_InsnOperandKind_SVE_SHRIMM_UNPRED_22,
    DA64_InsnOperandKind_SVE_SHRIMM_UNPRED,
    DA64_InsnOperandKind_SVE_SIMM5,
    DA64_InsnOperandKind_SVE_SIMM5B,
    DA64_InsnOperandKind_SVE_SIMM6,
    DA64_InsnOperandKind_SVE_SIMM8,
    DA64_InsnOperandKind_SVE_UIMM3,
    DA64_InsnOperandKind_SVE_UIMM7,
    DA64_InsnOperandKind_SVE_UIMM8_53,
    DA64_InsnOperandKind_SVE_UIMM8,
    DA64_InsnOperandKind_SVE_Vd,
    DA64_InsnOperandKind_SVE_Vm,
    DA64_InsnOperandKind_SVE_Vn,
    DA64_InsnOperandKind_SVE_VZn,
    DA64_InsnOperandKind_SVE_Za_16,
    DA64_InsnOperandKind_SVE_Za_5,
    DA64_InsnOperandKind_SVE_Zd,
    DA64_InsnOperandKind_SVE_Zm_16,
    DA64_InsnOperandKind_SVE_Zm_5,
    DA64_InsnOperandKind_SVE_Zm_imm4,
    DA64_InsnOperandKind_SVE_Zm3_11_INDEX,
    DA64_InsnOperandKind_SVE_Zm3_19_INDEX,
    DA64_InsnOperandKind_SVE_Zm3_22_INDEX,
    DA64_InsnOperandKind_SVE_Zm3_INDEX,
    DA64_InsnOperandKind_SVE_Zm4_11_INDEX,
    DA64_InsnOperandKind_SVE_Zm4_INDEX,
    DA64_InsnOperandKind_SVE_Zn_5_INDEX,
    DA64_InsnOperandKind_SVE_Zn_INDEX,
    DA64_InsnOperandKind_SVE_Zn,
    DA64_InsnOperandKind_SVE_ZnxN,
    DA64_InsnOperandKind_SVE_Zt,
    DA64_InsnOperandKind_SVE_ZtxN,
    DA64_InsnOperandKind_SYSREG_AT,
    DA64_InsnOperandKind_SYSREG_DC,
    DA64_InsnOperandKind_SYSREG_IC,
    DA64_InsnOperandKind_SYSREG_SR,
    DA64_InsnOperandKind_SYSREG_TLBI,
    DA64_InsnOperandKind_SYSREG_TLBIP,
    DA64_InsnOperandKind_SYSREG,
    DA64_InsnOperandKind_SYSREG128,
    DA64_InsnOperandKind_TME_UIMM16,
    DA64_InsnOperandKind_UIMM10,
    DA64_InsnOperandKind_UIMM3_OP1,
    DA64_InsnOperandKind_UIMM3_OP2,
    DA64_InsnOperandKind_UIMM4_ADDG,
    DA64_InsnOperandKind_UIMM4,
    DA64_InsnOperandKind_UIMM7,
    DA64_InsnOperandKind_UNDEFINED,
    DA64_InsnOperandKind_Va,
    DA64_InsnOperandKind_Vd,
    DA64_InsnOperandKind_VdD1,
    DA64_InsnOperandKind_Vm,
    DA64_InsnOperandKind_Vn,
    DA64_InsnOperandKind_VnD1,
    DA64_InsnOperandKind_WIDTH,
    DA64_InsnOperandKind_X16,
};

// The AArch64 instruction operand classes.
typedef enum DA64_InsnOperandClass DA64_InsnOperandClass;
enum DA64_InsnOperandClass {
    DA64_InsnOperandClass_ADDRESS,
    DA64_InsnOperandClass_COND,
    DA64_InsnOperandClass_FP_REG,
    DA64_InsnOperandClass_IMMEDIATE,
    DA64_InsnOperandClass_INT_REG,
    DA64_InsnOperandClass_MODIFIED_REG,
    DA64_InsnOperandClass_PRED_REG,
    DA64_InsnOperandClass_SIMD_ELEMENT,
    DA64_InsnOperandClass_SIMD_REG,
    DA64_InsnOperandClass_SIMD_REGLIST,
    DA64_InsnOperandClass_SISD_REG,
    DA64_InsnOperandClass_SVE_REG,
    DA64_InsnOperandClass_SVE_REGLIST,
    DA64_InsnOperandClass_SYSTEM,
    DA64_InsnOperandClass_ZA_ACCESS,
};

// The AArch64 instruction operand qualifiers.
typedef enum DA64_InsnOperandQualifier DA64_InsnOperandQualifier;
enum DA64_InsnOperandQualifier {
    DA64_InsnOperandQualifier_imm_0_15,
    DA64_InsnOperandQualifier_imm_0_31,
    DA64_InsnOperandQualifier_imm_0_63,
    DA64_InsnOperandQualifier_imm_0_7,
    DA64_InsnOperandQualifier_imm_1_32,
    DA64_InsnOperandQualifier_imm_1_64,
    DA64_InsnOperandQualifier_imm_tag,
    DA64_InsnOperandQualifier_LSL,
    DA64_InsnOperandQualifier_MSL,
    DA64_InsnOperandQualifier_P_M,
    DA64_InsnOperandQualifier_P_Z,
    DA64_InsnOperandQualifier_S_2H,
    DA64_InsnOperandQualifier_S_4B,
    DA64_InsnOperandQualifier_S_B,
    DA64_InsnOperandQualifier_S_D,
    DA64_InsnOperandQualifier_S_H,
    DA64_InsnOperandQualifier_S_Q,
    DA64_InsnOperandQualifier_S_S,
    DA64_InsnOperandQualifier_V_16B,
    DA64_InsnOperandQualifier_V_1D,
    DA64_InsnOperandQualifier_V_1Q,
    DA64_InsnOperandQualifier_V_2D,
    DA64_InsnOperandQualifier_V_2H,
    DA64_InsnOperandQualifier_V_2S,
    DA64_InsnOperandQualifier_V_4H,
    DA64_InsnOperandQualifier_V_4S,
    DA64_InsnOperandQualifier_V_8B,
    DA64_InsnOperandQualifier_V_8H,
    DA64_InsnOperandQualifier_W,
    DA64_InsnOperandQualifier_WSP,
    DA64_InsnOperandQualifier_X,
    DA64_InsnOperandQualifier_SP,
};

// The AArch64 instruction bit fields.
typedef enum DA64_InsnBitField DA64_InsnBitField;
enum DA64_InsnBitField {
    DA64_InsnBitField_b40,
    DA64_InsnBitField_b5,
    DA64_InsnBitField_cond,
    DA64_InsnBitField_CRm,
    DA64_InsnBitField_CRn,
    DA64_InsnBitField_CSSC_imm8,
    DA64_InsnBitField_imm1_0,
    DA64_InsnBitField_imm1_10,
    DA64_InsnBitField_imm1_15,
    DA64_InsnBitField_imm1_16,
    DA64_InsnBitField_imm1_2,
    DA64_InsnBitField_imm1_8,
    DA64_InsnBitField_imm12,
    DA64_InsnBitField_imm14,
    DA64_InsnBitField_imm16_0,
    DA64_InsnBitField_imm16_5,
    DA64_InsnBitField_imm19,
    DA64_InsnBitField_imm2_0,
    DA64_InsnBitField_imm2_1,
    DA64_InsnBitField_imm2_10,
    DA64_InsnBitField_imm2_12,
    DA64_InsnBitField_imm2_15,
    DA64_InsnBitField_imm2_16,
    DA64_InsnBitField_imm2_19,
    DA64_InsnBitField_imm2_8,
    DA64_InsnBitField_imm26,
    DA64_InsnBitField_imm3_0,
    DA64_InsnBitField_imm3_10,
    DA64_InsnBitField_imm3_12,
    DA64_InsnBitField_imm3_14,
    DA64_InsnBitField_imm3_15,
    DA64_InsnBitField_imm3_5,
    DA64_InsnBitField_imm4_0,
    DA64_InsnBitField_imm4_10,
    DA64_InsnBitField_imm4_11,
    DA64_InsnBitField_imm4_14,
    DA64_InsnBitField_imm4_5,
    DA64_InsnBitField_imm5,
    DA64_InsnBitField_imm6_10,
    DA64_InsnBitField_imm6_15,
    DA64_InsnBitField_imm7,
    DA64_InsnBitField_imm8,
    DA64_InsnBitField_imm9,
    DA64_InsnBitField_immhi,
    DA64_InsnBitField_immlo,
    DA64_InsnBitField_immr,
    DA64_InsnBitField_imms,
    DA64_InsnBitField_index,
    DA64_InsnBitField_index2,
    DA64_InsnBitField_LSE128_Rt,
    DA64_InsnBitField_LSE128_Rt2,
    DA64_InsnBitField_N,
    DA64_InsnBitField_nzcv,
    DA64_InsnBitField_off2,
    DA64_InsnBitField_off3,
    DA64_InsnBitField_ol,
    DA64_InsnBitField_op1,
    DA64_InsnBitField_op2,
    DA64_InsnBitField_opc2,
    DA64_InsnBitField_Ra,
    DA64_InsnBitField_Rd,
    DA64_InsnBitField_Rm,
    DA64_InsnBitField_Rn,
    DA64_InsnBitField_rotate1,
    DA64_InsnBitField_rotate2,
    DA64_InsnBitField_rotate3,
    DA64_InsnBitField_Rs,
    DA64_InsnBitField_Rt,
    DA64_InsnBitField_Rt2,
    DA64_InsnBitField_S_imm10,
    DA64_InsnBitField_scale,
    DA64_InsnBitField_shift,
    DA64_InsnBitField_SME_i1,
    DA64_InsnBitField_SME_Pdx2,
    DA64_InsnBitField_SME_Pm,
    DA64_InsnBitField_SME_PNd3,
    DA64_InsnBitField_SME_PNn3,
    DA64_InsnBitField_SME_Q,
    DA64_InsnBitField_SME_Rm,
    DA64_InsnBitField_SME_Rv,
    DA64_InsnBitField_SME_size_22,
    DA64_InsnBitField_SME_tszh,
    DA64_InsnBitField_SME_tszl,
    DA64_InsnBitField_SME_V,
    DA64_InsnBitField_SME_VL_10,
    DA64_InsnBitField_SME_VL_13,
    DA64_InsnBitField_SME_ZAda_2b,
    DA64_InsnBitField_SME_ZAda_3b,
    DA64_InsnBitField_SME_Zdn2,
    DA64_InsnBitField_SME_Zdn4,
    DA64_InsnBitField_SME_zero_mask,
    DA64_InsnBitField_SME_Zm,
    DA64_InsnBitField_SME_Zm2,
    DA64_InsnBitField_SME_Zm4,
    DA64_InsnBitField_SME_Zn2,
    DA64_InsnBitField_SME_Zn4,
    DA64_InsnBitField_SME_Zt2,
    DA64_InsnBitField_SME_Zt3,
    DA64_InsnBitField_SME_ZtT,
    DA64_InsnBitField_SVE_i1,
    DA64_InsnBitField_SVE_i2h,
    DA64_InsnBitField_SVE_i3h,
    DA64_InsnBitField_SVE_i3h2,
    DA64_InsnBitField_SVE_i3l,
    DA64_InsnBitField_SVE_imm3,
    DA64_InsnBitField_SVE_imm4,
    DA64_InsnBitField_SVE_imm5,
    DA64_InsnBitField_SVE_imm5b,
    DA64_InsnBitField_SVE_imm7,
    DA64_InsnBitField_SVE_imm8,
    DA64_InsnBitField_SVE_imm9,
    DA64_InsnBitField_SVE_immr,
    DA64_InsnBitField_SVE_imms,
    DA64_InsnBitField_SVE_N,
    DA64_InsnBitField_SVE_pattern,
    DA64_InsnBitField_SVE_Pd,
    DA64_InsnBitField_SVE_Pg3,
    DA64_InsnBitField_SVE_Pg4_10,
    DA64_InsnBitField_SVE_Pg4_16,
    DA64_InsnBitField_SVE_Pg4_5,
    DA64_InsnBitField_SVE_Pm,
    DA64_InsnBitField_SVE_Pn,
    DA64_InsnBitField_SVE_prfop,
    DA64_InsnBitField_SVE_Pt,
    DA64_InsnBitField_SVE_Rm,
    DA64_InsnBitField_SVE_Rn,
    DA64_InsnBitField_SVE_rot1,
    DA64_InsnBitField_SVE_rot2,
    DA64_InsnBitField_SVE_rot3,
    DA64_InsnBitField_SVE_sz,
    DA64_InsnBitField_SVE_tsz,
    DA64_InsnBitField_SVE_tszh,
    DA64_InsnBitField_SVE_tszl_19,
    DA64_InsnBitField_SVE_Vd,
    DA64_InsnBitField_SVE_Vm,
    DA64_InsnBitField_SVE_Vn,
    DA64_InsnBitField_SVE_xs_14,
    DA64_InsnBitField_SVE_xs_22,
    DA64_InsnBitField_SVE_Za_16,
    DA64_InsnBitField_SVE_Za_5,
    DA64_InsnBitField_SVE_Zd,
    DA64_InsnBitField_SVE_Zm_16,
    DA64_InsnBitField_SVE_Zm_5,
    DA64_InsnBitField_SVE_Zn,
    DA64_InsnBitField_SVE_Zt,
    DA64_InsnBitField_ZAn_1,
    DA64_InsnBitField_ZAn_2,
    DA64_InsnBitField_ZAn_3,
    DA64_InsnBitField_ZAn,
};

// The AArch64 instruction bit field specification.
typedef struct DA64_BitfieldSpec DA64_BitfieldSpec;
struct DA64_BitfieldSpec {
    DA64_InsnBitField bitfield;
    char lsb;
    char width;
};

/////////////////////////
//~ yuraiz: Secondary definitions

//! This module contains the definitions of the various enums,
//! using types that can be statically defined without allocations

// AArch64 instruction definitions.
typedef struct DA64_InsnOperand DA64_InsnOperand;
struct DA64_InsnOperand {
    DA64_InsnOperandKind kind;
    DA64_InsnOperandClass class;
    DA64_InsnOperandQualifier* qualifiers;
    da64_u64 qualifier_count;
    DA64_BitfieldSpec* bit_fields;
    da64_u64 bit_field_count;
};

// AArch64 instruction definitions.
typedef struct DA64_Insn DA64_Insn;
struct DA64_Insn {
    char* mnemonic;
    da64_u64 mnemonic_size;
    DA64_Insn* aliases;
    da64_u64 alias_count;
    da64_u32 opcode;
    da64_u32 mask;
    DA64_InsnClass class;
    DA64_InsnFeatureSet feature_set;
    DA64_InsnOperand* operands;
    da64_u64 operand_count;
    DA64_InsnFlags flags;
};

// String tables

const static da64_str8 da64_op_kind_to_str8[] = {
    da64_str8_lit("ADDR_ADRP"),
    da64_str8_lit("ADDR_OFFSET"),
    da64_str8_lit("ADDR_PCREL14"),
    da64_str8_lit("ADDR_PCREL19"),
    da64_str8_lit("ADDR_PCREL21"),
    da64_str8_lit("ADDR_PCREL26"),
    da64_str8_lit("ADDR_REGOFF"),
    da64_str8_lit("ADDR_SIMM10"),
    da64_str8_lit("ADDR_SIMM11"),
    da64_str8_lit("ADDR_SIMM13"),
    da64_str8_lit("ADDR_SIMM7"),
    da64_str8_lit("ADDR_SIMM9"),
    da64_str8_lit("ADDR_SIMPLE"),
    da64_str8_lit("ADDR_UIMM12"),
    da64_str8_lit("AIMM"),
    da64_str8_lit("BARRIER_DSB_NXS"),
    da64_str8_lit("BARRIER_GCSB"),
    da64_str8_lit("BARRIER_ISB"),
    da64_str8_lit("BARRIER_PSB"),
    da64_str8_lit("BARRIER"),
    da64_str8_lit("BIT_NUM"),
    da64_str8_lit("BTI_TARGET"),
    da64_str8_lit("CCMP_IMM"),
    da64_str8_lit("COND"),
    da64_str8_lit("COND1"),
    da64_str8_lit("CRm"),
    da64_str8_lit("CRn"),
    da64_str8_lit("CSSC_SIMM8"),
    da64_str8_lit("CSSC_UIMM8"),
    da64_str8_lit("Ed"),
    da64_str8_lit("Em"),
    da64_str8_lit("Em16"),
    da64_str8_lit("En"),
    da64_str8_lit("EXCEPTION"),
    da64_str8_lit("Fa"),
    da64_str8_lit("FBITS"),
    da64_str8_lit("Fd"),
    da64_str8_lit("Fm"),
    da64_str8_lit("Fn"),
    da64_str8_lit("FPIMM"),
    da64_str8_lit("FPIMM0"),
    da64_str8_lit("Ft"),
    da64_str8_lit("Ft2"),
    da64_str8_lit("HALF"),
    da64_str8_lit("IDX"),
    da64_str8_lit("IMM_2"),
    da64_str8_lit("IMM_MOV"),
    da64_str8_lit("IMM_ROT1"),
    da64_str8_lit("IMM_ROT2"),
    da64_str8_lit("IMM_ROT3"),
    da64_str8_lit("IMM_VLSL"),
    da64_str8_lit("IMM_VLSR"),
    da64_str8_lit("IMM"),
    da64_str8_lit("IMM0"),
    da64_str8_lit("IMMR"),
    da64_str8_lit("IMMS"),
    da64_str8_lit("LEt"),
    da64_str8_lit("LIMM"),
    da64_str8_lit("LSE128_Rt"),
    da64_str8_lit("LSE128_Rt2"),
    da64_str8_lit("LVn"),
    da64_str8_lit("LVt_AL"),
    da64_str8_lit("LVt"),
    da64_str8_lit("MASK"),
    da64_str8_lit("MOPS_ADDR_Rd"),
    da64_str8_lit("MOPS_ADDR_Rs"),
    da64_str8_lit("MOPS_WB_Rn"),
    da64_str8_lit("NZCV"),
    da64_str8_lit("PAIRREG_OR_XZR"),
    da64_str8_lit("PAIRREG"),
    da64_str8_lit("PRFOP"),
    da64_str8_lit("PSTATEFIELD"),
    da64_str8_lit("Ra"),
    da64_str8_lit("RCPC3_ADDR_OFFSET"),
    da64_str8_lit("RCPC3_ADDR_OPT_POSTIND"),
    da64_str8_lit("RCPC3_ADDR_OPT_PREIND_WB"),
    da64_str8_lit("RCPC3_ADDR_POSTIND"),
    da64_str8_lit("RCPC3_ADDR_PREIND_WB"),
    da64_str8_lit("Rd_SP"),
    da64_str8_lit("Rd"),
    da64_str8_lit("Rm_EXT"),
    da64_str8_lit("Rm_SFT"),
    da64_str8_lit("Rm_SP"),
    da64_str8_lit("Rm"),
    da64_str8_lit("Rn_SP"),
    da64_str8_lit("Rn"),
    da64_str8_lit("RPRFMOP"),
    da64_str8_lit("Rs"),
    da64_str8_lit("Rt_LS64"),
    da64_str8_lit("Rt_SP"),
    da64_str8_lit("Rt_SYS"),
    da64_str8_lit("Rt"),
    da64_str8_lit("Rt2"),
    da64_str8_lit("Sd"),
    da64_str8_lit("SHLL_IMM"),
    da64_str8_lit("SIMD_ADDR_POST"),
    da64_str8_lit("SIMD_ADDR_SIMPLE"),
    da64_str8_lit("SIMD_FPIMM"),
    da64_str8_lit("SIMD_IMM_SFT"),
    da64_str8_lit("SIMD_IMM"),
    da64_str8_lit("SIMM5"),
    da64_str8_lit("Sm"),
    da64_str8_lit("SME_ADDR_RI_U4xVL"),
    da64_str8_lit("SME_list_of_64bit_tiles"),
    da64_str8_lit("SME_Pdx2"),
    da64_str8_lit("SME_PdxN"),
    da64_str8_lit("SME_Pm"),
    da64_str8_lit("SME_PNd3"),
    da64_str8_lit("SME_PNg3"),
    da64_str8_lit("SME_PNn"),
    da64_str8_lit("SME_PNn3_INDEX1"),
    da64_str8_lit("SME_PNn3_INDEX2"),
    da64_str8_lit("SME_PnT_Wm_imm"),
    da64_str8_lit("SME_SHRIMM4"),
    da64_str8_lit("SME_SHRIMM5"),
    da64_str8_lit("SME_SM_ZA"),
    da64_str8_lit("SME_VLxN_10"),
    da64_str8_lit("SME_VLxN_13"),
    da64_str8_lit("SME_ZA_array_off1x4"),
    da64_str8_lit("SME_ZA_array_off2x2"),
    da64_str8_lit("SME_ZA_array_off2x4"),
    da64_str8_lit("SME_ZA_array_off3_0"),
    da64_str8_lit("SME_ZA_array_off3_5"),
    da64_str8_lit("SME_ZA_array_off3x2"),
    da64_str8_lit("SME_ZA_array_off4"),
    da64_str8_lit("SME_ZA_array_vrsb_1"),
    da64_str8_lit("SME_ZA_array_vrsb_2"),
    da64_str8_lit("SME_ZA_array_vrsd_1"),
    da64_str8_lit("SME_ZA_array_vrsd_2"),
    da64_str8_lit("SME_ZA_array_vrsh_1"),
    da64_str8_lit("SME_ZA_array_vrsh_2"),
    da64_str8_lit("SME_ZA_array_vrss_1"),
    da64_str8_lit("SME_ZA_array_vrss_2"),
    da64_str8_lit("SME_ZA_HV_idx_dest"),
    da64_str8_lit("SME_ZA_HV_idx_destxN"),
    da64_str8_lit("SME_ZA_HV_idx_ldstr"),
    da64_str8_lit("SME_ZA_HV_idx_src"),
    da64_str8_lit("SME_ZA_HV_idx_srcxN"),
    da64_str8_lit("SME_ZAda_2b"),
    da64_str8_lit("SME_ZAda_3b"),
    da64_str8_lit("SME_Zdnx2"),
    da64_str8_lit("SME_Zdnx4"),
    da64_str8_lit("SME_Zm_INDEX1"),
    da64_str8_lit("SME_Zm_INDEX2"),
    da64_str8_lit("SME_Zm_INDEX3_1"),
    da64_str8_lit("SME_Zm_INDEX3_10"),
    da64_str8_lit("SME_Zm_INDEX3_2"),
    da64_str8_lit("SME_Zm_INDEX4_1"),
    da64_str8_lit("SME_Zm_INDEX4_10"),
    da64_str8_lit("SME_Zm"),
    da64_str8_lit("SME_Zmx2"),
    da64_str8_lit("SME_Zmx4"),
    da64_str8_lit("SME_Zn_INDEX1_16"),
    da64_str8_lit("SME_Zn_INDEX2_15"),
    da64_str8_lit("SME_Zn_INDEX2_16"),
    da64_str8_lit("SME_Zn_INDEX3_14"),
    da64_str8_lit("SME_Zn_INDEX3_15"),
    da64_str8_lit("SME_Zn_INDEX4_14"),
    da64_str8_lit("SME_Znx2"),
    da64_str8_lit("SME_Znx4"),
    da64_str8_lit("SME_ZT0_INDEX"),
    da64_str8_lit("SME_ZT0_LIST"),
    da64_str8_lit("SME_ZT0"),
    da64_str8_lit("SME_Zt2"),
    da64_str8_lit("SME_Zt3"),
    da64_str8_lit("SME_Zt4"),
    da64_str8_lit("SME_Ztx2_STRIDED"),
    da64_str8_lit("SME_Ztx4_STRIDED"),
    da64_str8_lit("Sn"),
    da64_str8_lit("SVE_ADDR_R"),
    da64_str8_lit("SVE_ADDR_RI_S4x16"),
    da64_str8_lit("SVE_ADDR_RI_S4x2xVL"),
    da64_str8_lit("SVE_ADDR_RI_S4x32"),
    da64_str8_lit("SVE_ADDR_RI_S4x3xVL"),
    da64_str8_lit("SVE_ADDR_RI_S4x4xVL"),
    da64_str8_lit("SVE_ADDR_RI_S4xVL"),
    da64_str8_lit("SVE_ADDR_RI_S6xVL"),
    da64_str8_lit("SVE_ADDR_RI_S9xVL"),
    da64_str8_lit("SVE_ADDR_RI_U6"),
    da64_str8_lit("SVE_ADDR_RI_U6x2"),
    da64_str8_lit("SVE_ADDR_RI_U6x4"),
    da64_str8_lit("SVE_ADDR_RI_U6x8"),
    da64_str8_lit("SVE_ADDR_RR_LSL1"),
    da64_str8_lit("SVE_ADDR_RR_LSL2"),
    da64_str8_lit("SVE_ADDR_RR_LSL3"),
    da64_str8_lit("SVE_ADDR_RR_LSL4"),
    da64_str8_lit("SVE_ADDR_RR"),
    da64_str8_lit("SVE_ADDR_RX_LSL1"),
    da64_str8_lit("SVE_ADDR_RX_LSL2"),
    da64_str8_lit("SVE_ADDR_RX_LSL3"),
    da64_str8_lit("SVE_ADDR_RX"),
    da64_str8_lit("SVE_ADDR_RZ_LSL1"),
    da64_str8_lit("SVE_ADDR_RZ_LSL2"),
    da64_str8_lit("SVE_ADDR_RZ_LSL3"),
    da64_str8_lit("SVE_ADDR_RZ_XTW_14"),
    da64_str8_lit("SVE_ADDR_RZ_XTW_22"),
    da64_str8_lit("SVE_ADDR_RZ_XTW1_14"),
    da64_str8_lit("SVE_ADDR_RZ_XTW1_22"),
    da64_str8_lit("SVE_ADDR_RZ_XTW2_14"),
    da64_str8_lit("SVE_ADDR_RZ_XTW2_22"),
    da64_str8_lit("SVE_ADDR_RZ_XTW3_14"),
    da64_str8_lit("SVE_ADDR_RZ_XTW3_22"),
    da64_str8_lit("SVE_ADDR_RZ"),
    da64_str8_lit("SVE_ADDR_ZI_U5"),
    da64_str8_lit("SVE_ADDR_ZI_U5x2"),
    da64_str8_lit("SVE_ADDR_ZI_U5x4"),
    da64_str8_lit("SVE_ADDR_ZI_U5x8"),
    da64_str8_lit("SVE_ADDR_ZX"),
    da64_str8_lit("SVE_ADDR_ZZ_LSL"),
    da64_str8_lit("SVE_ADDR_ZZ_SXTW"),
    da64_str8_lit("SVE_ADDR_ZZ_UXTW"),
    da64_str8_lit("SVE_AIMM"),
    da64_str8_lit("SVE_ASIMM"),
    da64_str8_lit("SVE_FPIMM8"),
    da64_str8_lit("SVE_I1_HALF_ONE"),
    da64_str8_lit("SVE_I1_HALF_TWO"),
    da64_str8_lit("SVE_I1_ZERO_ONE"),
    da64_str8_lit("SVE_IMM_ROT1"),
    da64_str8_lit("SVE_IMM_ROT2"),
    da64_str8_lit("SVE_IMM_ROT3"),
    da64_str8_lit("SVE_INV_LIMM"),
    da64_str8_lit("SVE_LIMM_MOV"),
    da64_str8_lit("SVE_LIMM"),
    da64_str8_lit("SVE_PATTERN_SCALED"),
    da64_str8_lit("SVE_PATTERN"),
    da64_str8_lit("SVE_Pd"),
    da64_str8_lit("SVE_Pg3"),
    da64_str8_lit("SVE_Pg4_10"),
    da64_str8_lit("SVE_Pg4_16"),
    da64_str8_lit("SVE_Pg4_5"),
    da64_str8_lit("SVE_Pm"),
    da64_str8_lit("SVE_Pn"),
    da64_str8_lit("SVE_PNd"),
    da64_str8_lit("SVE_PNg4_10"),
    da64_str8_lit("SVE_PNn"),
    da64_str8_lit("SVE_PNt"),
    da64_str8_lit("SVE_PRFOP"),
    da64_str8_lit("SVE_Pt"),
    da64_str8_lit("SVE_Rm"),
    da64_str8_lit("SVE_Rn_SP"),
    da64_str8_lit("SVE_SHLIMM_PRED"),
    da64_str8_lit("SVE_SHLIMM_UNPRED_22"),
    da64_str8_lit("SVE_SHLIMM_UNPRED"),
    da64_str8_lit("SVE_SHRIMM_PRED"),
    da64_str8_lit("SVE_SHRIMM_UNPRED_22"),
    da64_str8_lit("SVE_SHRIMM_UNPRED"),
    da64_str8_lit("SVE_SIMM5"),
    da64_str8_lit("SVE_SIMM5B"),
    da64_str8_lit("SVE_SIMM6"),
    da64_str8_lit("SVE_SIMM8"),
    da64_str8_lit("SVE_UIMM3"),
    da64_str8_lit("SVE_UIMM7"),
    da64_str8_lit("SVE_UIMM8_53"),
    da64_str8_lit("SVE_UIMM8"),
    da64_str8_lit("SVE_Vd"),
    da64_str8_lit("SVE_Vm"),
    da64_str8_lit("SVE_Vn"),
    da64_str8_lit("SVE_VZn"),
    da64_str8_lit("SVE_Za_16"),
    da64_str8_lit("SVE_Za_5"),
    da64_str8_lit("SVE_Zd"),
    da64_str8_lit("SVE_Zm_16"),
    da64_str8_lit("SVE_Zm_5"),
    da64_str8_lit("SVE_Zm_imm4"),
    da64_str8_lit("SVE_Zm3_11_INDEX"),
    da64_str8_lit("SVE_Zm3_19_INDEX"),
    da64_str8_lit("SVE_Zm3_22_INDEX"),
    da64_str8_lit("SVE_Zm3_INDEX"),
    da64_str8_lit("SVE_Zm4_11_INDEX"),
    da64_str8_lit("SVE_Zm4_INDEX"),
    da64_str8_lit("SVE_Zn_5_INDEX"),
    da64_str8_lit("SVE_Zn_INDEX"),
    da64_str8_lit("SVE_Zn"),
    da64_str8_lit("SVE_ZnxN"),
    da64_str8_lit("SVE_Zt"),
    da64_str8_lit("SVE_ZtxN"),
    da64_str8_lit("SYSREG_AT"),
    da64_str8_lit("SYSREG_DC"),
    da64_str8_lit("SYSREG_IC"),
    da64_str8_lit("SYSREG_SR"),
    da64_str8_lit("SYSREG_TLBI"),
    da64_str8_lit("SYSREG_TLBIP"),
    da64_str8_lit("SYSREG"),
    da64_str8_lit("SYSREG128"),
    da64_str8_lit("TME_UIMM16"),
    da64_str8_lit("UIMM10"),
    da64_str8_lit("UIMM3_OP1"),
    da64_str8_lit("UIMM3_OP2"),
    da64_str8_lit("UIMM4_ADDG"),
    da64_str8_lit("UIMM4"),
    da64_str8_lit("UIMM7"),
    da64_str8_lit("UNDEFINED"),
    da64_str8_lit("Va"),
    da64_str8_lit("Vd"),
    da64_str8_lit("VdD1"),
    da64_str8_lit("Vm"),
    da64_str8_lit("Vn"),
    da64_str8_lit("VnD1"),
    da64_str8_lit("WIDTH"),
    da64_str8_lit("X16"),
};
